//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.
package self_contained

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

// Each marked enum type is referenced here so that its enum() marker is used
// from production code and keeps the shape the generator requires.
var (
	_ interface{ enum() } = *new(Priority)
	_ interface{ enum() } = *new(Severity)
)

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (Issue) Schema() json.RawMessage {
	const fileName = "jsonschema/Issue.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
