//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package optionality

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	yaml "go.yaml.in/yaml/v4"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property '!type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Config        *jsonschema.Schema
	__gen_jsonschema_compiled_NumericConfig *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Config
		__gen_jsonschema_compiled_Config = compile("Config", __zero.Schema())
	}

	{
		var __zero NumericConfig
		__gen_jsonschema_compiled_NumericConfig = compile("NumericConfig", __zero.Schema())
	}
}

func (Config) Schema() json.RawMessage {
	const fileName = "jsonschema/Config.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (NumericConfig) Schema() json.RawMessage {
	const fileName = "jsonschema/NumericConfig.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Config.
func (Config) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Config.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for NumericConfig.
func (NumericConfig) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_NumericConfig.Validate(inst)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Config.
func (c *Config) UnmarshalJSON(data []byte) (err error) {
	type Alias Config
	type Wrapper struct {
		Alias
		Pet json.RawMessage `json:"pet,omitzero"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Config(wrapper.Alias)

	if len(wrapper.Pet) > 0 {
		if __next.Pet.Value, err = __jsonUnmarshal__optionality__Pet__Config__Pet(wrapper.Pet); err != nil {
			return err
		}
		__next.Pet.Present = true
	}

	*c = __next
	return nil
}

// UnmarshalYAML is a generated custom yaml.Unmarshaler implementation for
// Config.
func (c *Config) UnmarshalYAML(node *yaml.Node) (err error) {
	var fields map[string]yaml.Node
	if err = node.Decode(&fields); err != nil {
		return err
	}
	ordinary := make(map[string]yaml.Node, len(fields))
	for name, value := range fields {
		ordinary[name] = value
	}
	delete(ordinary, "pet")
	type Alias Config
	var alias Alias
	ordinaryNode := __jsonschema__yamlMappingNode(ordinary)
	if err = ordinaryNode.Decode(&alias); err != nil {
		return err
	}
	__next := Config(alias)

	if __node0, ok := fields["pet"]; ok {
		if __next.Pet.Value, err = __yamlUnmarshal__optionality__Pet__Config__Pet(&__node0); err != nil {
			return err
		}
		__next.Pet.Present = true
	}

	*c = __next
	return nil
}
func __jsonUnmarshal__optionality__Pet__Config__Pet(data []byte) (Pet, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Dog":
		var obj Dog
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Cat":
		var obj Cat
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __yamlUnmarshal__optionality__Pet__Config__Pet(node *yaml.Node) (Pet, error) {
	var temp map[string]yaml.Node
	if err := node.Decode(&temp); err != nil {
		return nil, err
	}
	discriminatorNode, ok := temp["!kind"]
	if !ok {
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	}
	var discriminator string
	if err := discriminatorNode.Decode(&discriminator); err != nil {
		return nil, fmt.Errorf("unable to unmarshal discriminator value %q: %w", discriminatorNode.Value, err)
	}
	switch discriminator {
	case "Dog":
		var obj Dog
		if err := node.Decode(&obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Cat":
		var obj Cat
		if err := node.Decode(&obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}

func __jsonschema__yamlMappingNode(fields map[string]yaml.Node) yaml.Node {
	content := make([]*yaml.Node, 0, len(fields)*2)
	for name, value := range fields {
		nameNode := yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: name}
		valueNode := value
		content = append(content, &nameNode, &valueNode)
	}
	return yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", Content: content}
}
