//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.
package consumer

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (Detail) Schema() json.RawMessage {
	const fileName = "jsonschema/Detail.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Composition) Schema() json.RawMessage {
	const fileName = "jsonschema/Composition.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Envelope) Schema() json.RawMessage {
	const fileName = "jsonschema/Envelope.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Envelope.
func (e Envelope) MarshalJSON() ([]byte, error) {
	type Alias Envelope
	type Wrapper struct {
		Alias
		Event        json.RawMessage `json:"event"`
		Other        json.RawMessage `json:"other"`
		Maybe        json.RawMessage `json:"maybe,omitzero"`
		Events       json.RawMessage `json:"events"`
		PriorityName json.RawMessage `json:"priority_name"`
	}
	wrapper := Wrapper{Alias: Alias(e)}
	var err error

	if wrapper.Event, err = __jsonMarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(e.Event); err != nil {
		return nil, fmt.Errorf("field event: %w", err)
	}

	if wrapper.Other, err = __jsonMarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(e.Other); err != nil {
		return nil, fmt.Errorf("field other: %w", err)
	}

	if e.Maybe.Present {
		if wrapper.Maybe, err = __jsonMarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(e.Maybe.Value); err != nil {
			return nil, fmt.Errorf("field maybe: %w", err)
		}
	}

	if e.Events == nil {
		return nil, fmt.Errorf("field events: nil registered interface slice")
	}
	__raw3 := make([]json.RawMessage, len(e.Events))
	for __index, __value := range e.Events {
		if __raw3[__index], err = __jsonMarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(__value); err != nil {
			return nil, fmt.Errorf("field events[%d]: %w", __index, err)
		}
	}
	if wrapper.Events, err = json.Marshal(__raw3); err != nil {
		return nil, fmt.Errorf("field events: %w", err)
	}

	if wrapper.PriorityName, err = __jsonMarshalEnum__Envelope__PriorityName(e.PriorityName); err != nil {
		return nil, fmt.Errorf("field priority_name: %w", err)
	}

	return json.Marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Envelope.
func (e *Envelope) UnmarshalJSON(data []byte) (err error) {
	type Alias Envelope
	type Wrapper struct {
		Alias
		Event        json.RawMessage `json:"event"`
		Other        json.RawMessage `json:"other"`
		Maybe        json.RawMessage `json:"maybe,omitzero"`
		Events       json.RawMessage `json:"events"`
		PriorityName json.RawMessage `json:"priority_name"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Envelope(wrapper.Alias)

	var __decoded0 Event
	if __decoded0, err = __jsonUnmarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(wrapper.Event); err != nil {
		return err
	}
	__next.Event = __decoded0

	var __decoded1 Event
	if __decoded1, err = __jsonUnmarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(wrapper.Other); err != nil {
		return err
	}
	__next.Other = __decoded1

	if len(wrapper.Maybe) > 0 {
		var __decoded2 Event
		if __decoded2, err = __jsonUnmarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(wrapper.Maybe); err != nil {
			return err
		}
		__next.Maybe.Value = __decoded2
		__next.Maybe.Present = true
	}

	if len(wrapper.Events) > 0 {
		var __raw3 []json.RawMessage
		if err = json.Unmarshal(wrapper.Events, &__raw3); err != nil {
			return fmt.Errorf("field events: %w", err)
		}
		var __decoded3 []Event
		if __raw3 != nil {
			__decoded3 = make([]Event, len(__raw3))
		}
		for __index, __raw := range __raw3 {
			if __decoded3[__index], err = __jsonUnmarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(__raw); err != nil {
				return fmt.Errorf("field events[%d]: %w", __index, err)
			}
		}
		__next.Events = __decoded3
	}

	var __enumDecoded0 Priority
	if __enumDecoded0, err = __jsonUnmarshalEnum__Envelope__PriorityName(wrapper.PriorityName); err != nil {
		return fmt.Errorf("field priority_name: %w", err)
	}
	__next.PriorityName = __enumDecoded0

	*e = __next
	return nil
}

func __jsonMarshalEnum__Envelope__PriorityName(value Priority) (json.RawMessage, error) {
	switch value {
	case Low:
		return json.Marshal("Low")
	case High:
		return json.Marshal("High")
	case Urgent:
		return json.Marshal("Urgent")
	case Medium:
		return json.Marshal("Medium")
	default:
		return nil, errors.New("undeclared value for string-mode enum Priority")
	}
}

func __jsonUnmarshalEnum__Envelope__PriorityName(data []byte) (Priority, error) {
	var zero Priority
	if __jsonschema__isJSONNull(data) {
		return zero, errors.New("string-mode enum Priority cannot be JSON null")
	}
	var wire string
	if err := json.Unmarshal(data, &wire); err != nil {
		return zero, fmt.Errorf("string-mode enum Priority requires a JSON string: %w", err)
	}
	switch wire {
	case "Low":
		return Low, nil
	case "High":
		return High, nil
	case "Urgent":
		return Urgent, nil
	case "Medium":
		return Medium, nil
	default:
		return zero, fmt.Errorf("unknown string-mode enum Priority name %q", wire)
	}
}
func __jsonschema__isJSONNull(data []byte) bool {
	return bytes.Equal(bytes.TrimSpace(data), []byte("null"))
}
func __jsonMarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "Created"
		data, err = json.Marshal(&object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "Deleted"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"!kind",
		discriminator,
	)
}

func __jsonUnmarshal__consumer__Event__0b7f42625d78b5f39ad6eed9e1b62db8b2e97f692b1a896560991f2a2a013f67(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Created":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Deleted":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := json.Marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return json.Marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
