//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package ref_types

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property '!type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Shared         *jsonschema.Schema
	__gen_jsonschema_compiled_Container      *jsonschema.Schema
	__gen_jsonschema_compiled_NullableConfig *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Shared
		__gen_jsonschema_compiled_Shared = compile("Shared", __zero.Schema())
	}

	{
		var __zero Container
		__gen_jsonschema_compiled_Container = compile("Container", __zero.Schema())
	}

	{
		var __zero NullableConfig
		__gen_jsonschema_compiled_NullableConfig = compile("NullableConfig", __zero.Schema())
	}
}

func (Shared) Schema() json.RawMessage {
	const fileName = "jsonschema/Shared.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Container) Schema() json.RawMessage {
	const fileName = "jsonschema/Container.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (NullableConfig) Schema() json.RawMessage {
	const fileName = "jsonschema/NullableConfig.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Shared.
func (Shared) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Shared.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Container.
func (Container) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Container.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for NullableConfig.
func (NullableConfig) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_NullableConfig.Validate(inst)
}
