//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package boundary

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Pair   *jsonschema.Schema
	__gen_jsonschema_compiled_Config *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Pair
		__gen_jsonschema_compiled_Pair = compile("Pair", __zero.Schema())
	}

	{
		var __zero Config
		__gen_jsonschema_compiled_Config = compile("Config", __zero.Schema())
	}
}

func (Pair) Schema() json.RawMessage {
	const fileName = "jsonschema/Pair.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Config) Schema() json.RawMessage {
	const fileName = "jsonschema/Config.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Pair.
func (Pair) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Pair.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Config.
func (Config) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Config.Validate(inst)
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Config.
func (c Config) MarshalJSON() ([]byte, error) {
	type Alias Config
	type Wrapper struct {
		Alias
		Direct   json.RawMessage `json:"direct"`
		Nullable json.RawMessage `json:"nullable"`
		Optional json.RawMessage `json:"optional,omitzero"`
	}
	wrapper := Wrapper{Alias: Alias(c)}
	var err error

	if wrapper.Direct, err = __jsonMarshalEnum__Config__Direct(c.Direct); err != nil {
		return nil, fmt.Errorf("field direct: %w", err)
	}

	if c.Nullable.Present {
		if wrapper.Nullable, err = __jsonMarshalEnum__Config__Nullable(c.Nullable.Value); err != nil {
			return nil, fmt.Errorf("field nullable: %w", err)
		}
	} else {
		wrapper.Nullable = json.RawMessage("null")
	}

	if c.Optional.Present {
		if wrapper.Optional, err = __jsonMarshalEnum__Config__Optional(c.Optional.Value); err != nil {
			return nil, fmt.Errorf("field optional: %w", err)
		}
	}

	return json.Marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Config.
func (c *Config) UnmarshalJSON(data []byte) (err error) {
	type Alias Config
	type Wrapper struct {
		Alias
		Direct   json.RawMessage `json:"direct"`
		Nullable json.RawMessage `json:"nullable"`
		Optional json.RawMessage `json:"optional,omitzero"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Config(wrapper.Alias)

	var __enumDecoded0 Mode
	if __enumDecoded0, err = __jsonUnmarshalEnum__Config__Direct(wrapper.Direct); err != nil {
		return fmt.Errorf("field direct: %w", err)
	}
	__next.Direct = __enumDecoded0

	if len(wrapper.Nullable) == 0 {
		return fmt.Errorf("field nullable: required nullable string-mode enum is missing")
	}
	if !__jsonschema__isJSONNull(wrapper.Nullable) {
		var __enumDecoded1 Mode
		if __enumDecoded1, err = __jsonUnmarshalEnum__Config__Nullable(wrapper.Nullable); err != nil {
			return fmt.Errorf("field nullable: %w", err)
		}
		__next.Nullable.Value = __enumDecoded1
		__next.Nullable.Present = true
	}

	if len(wrapper.Optional) > 0 {
		if __jsonschema__isJSONNull(wrapper.Optional) {
			return fmt.Errorf("field optional: Optional value cannot be JSON null")
		}
		var __enumDecoded2 Mode
		if __enumDecoded2, err = __jsonUnmarshalEnum__Config__Optional(wrapper.Optional); err != nil {
			return fmt.Errorf("field optional: %w", err)
		}
		__next.Optional.Value = __enumDecoded2
		__next.Optional.Present = true
	}

	*c = __next
	return nil
}

func __jsonMarshalEnum__Config__Direct(value Mode) (json.RawMessage, error) {
	switch value {
	case Quiet:
		return json.Marshal("Quiet")
	case Loud:
		return json.Marshal("Loud")
	default:
		return nil, errors.New("undeclared value for string-mode enum Mode")
	}
}

func __jsonUnmarshalEnum__Config__Direct(data []byte) (Mode, error) {
	var zero Mode
	if __jsonschema__isJSONNull(data) {
		return zero, errors.New("string-mode enum Mode cannot be JSON null")
	}
	var wire string
	if err := json.Unmarshal(data, &wire); err != nil {
		return zero, fmt.Errorf("string-mode enum Mode requires a JSON string: %w", err)
	}
	switch wire {
	case "Quiet":
		return Quiet, nil
	case "Loud":
		return Loud, nil
	default:
		return zero, fmt.Errorf("unknown string-mode enum Mode name %q", wire)
	}
}
func __jsonMarshalEnum__Config__Nullable(value Mode) (json.RawMessage, error) {
	switch value {
	case Quiet:
		return json.Marshal("Quiet")
	case Loud:
		return json.Marshal("Loud")
	default:
		return nil, errors.New("undeclared value for string-mode enum Mode")
	}
}

func __jsonUnmarshalEnum__Config__Nullable(data []byte) (Mode, error) {
	var zero Mode
	if __jsonschema__isJSONNull(data) {
		return zero, errors.New("string-mode enum Mode cannot be JSON null")
	}
	var wire string
	if err := json.Unmarshal(data, &wire); err != nil {
		return zero, fmt.Errorf("string-mode enum Mode requires a JSON string: %w", err)
	}
	switch wire {
	case "Quiet":
		return Quiet, nil
	case "Loud":
		return Loud, nil
	default:
		return zero, fmt.Errorf("unknown string-mode enum Mode name %q", wire)
	}
}
func __jsonMarshalEnum__Config__Optional(value Mode) (json.RawMessage, error) {
	switch value {
	case Quiet:
		return json.Marshal("Quiet")
	case Loud:
		return json.Marshal("Loud")
	default:
		return nil, errors.New("undeclared value for string-mode enum Mode")
	}
}

func __jsonUnmarshalEnum__Config__Optional(data []byte) (Mode, error) {
	var zero Mode
	if __jsonschema__isJSONNull(data) {
		return zero, errors.New("string-mode enum Mode cannot be JSON null")
	}
	var wire string
	if err := json.Unmarshal(data, &wire); err != nil {
		return zero, fmt.Errorf("string-mode enum Mode requires a JSON string: %w", err)
	}
	switch wire {
	case "Quiet":
		return Quiet, nil
	case "Loud":
		return Loud, nil
	default:
		return zero, fmt.Errorf("unknown string-mode enum Mode name %q", wire)
	}
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Pair.
func (p Pair) MarshalJSON() ([]byte, error) {
	type Alias Pair
	type Wrapper struct {
		Alias
		Left   json.RawMessage `json:"left"`
		Right  json.RawMessage `json:"right"`
		Events json.RawMessage `json:"events"`
		Extra  json.RawMessage `json:"extra,omitzero"`
	}
	wrapper := Wrapper{Alias: Alias(p)}
	var err error

	if wrapper.Left, err = __jsonMarshal__boundary__Event__9765682108c55bc1ada1376e4af4a6c2cc9965bfab7611e790f53644f0e31217(p.Left); err != nil {
		return nil, fmt.Errorf("field left: %w", err)
	}

	if wrapper.Right, err = __jsonMarshal__boundary__Event__e6e32185f0aa20dcba2a18e25286e1f6d044f1f4e4f7a00366f124a88686d13e(p.Right); err != nil {
		return nil, fmt.Errorf("field right: %w", err)
	}

	if p.Events == nil {
		return nil, fmt.Errorf("field events: nil registered interface slice")
	}
	__raw2 := make([]json.RawMessage, len(p.Events))
	for __index, __value := range p.Events {
		if __raw2[__index], err = __jsonMarshal__boundary__Event__14033c5e11b7c19bb4b06e0f889fd3440bb71b6e3d80a60245f6e5f100c928f6(__value); err != nil {
			return nil, fmt.Errorf("field events[%d]: %w", __index, err)
		}
	}
	if wrapper.Events, err = json.Marshal(__raw2); err != nil {
		return nil, fmt.Errorf("field events: %w", err)
	}

	if p.Extra.Present {
		if wrapper.Extra, err = __jsonMarshal__boundary__Event__14033c5e11b7c19bb4b06e0f889fd3440bb71b6e3d80a60245f6e5f100c928f6(p.Extra.Value); err != nil {
			return nil, fmt.Errorf("field extra: %w", err)
		}
	}

	return json.Marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Pair.
func (p *Pair) UnmarshalJSON(data []byte) (err error) {
	type Alias Pair
	type Wrapper struct {
		Alias
		Left   json.RawMessage `json:"left"`
		Right  json.RawMessage `json:"right"`
		Events json.RawMessage `json:"events"`
		Extra  json.RawMessage `json:"extra,omitzero"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Pair(wrapper.Alias)

	var __decoded0 Event
	if __decoded0, err = __jsonUnmarshal__boundary__Event__9765682108c55bc1ada1376e4af4a6c2cc9965bfab7611e790f53644f0e31217(wrapper.Left); err != nil {
		return err
	}
	__next.Left = __decoded0

	var __decoded1 Event
	if __decoded1, err = __jsonUnmarshal__boundary__Event__e6e32185f0aa20dcba2a18e25286e1f6d044f1f4e4f7a00366f124a88686d13e(wrapper.Right); err != nil {
		return err
	}
	__next.Right = __decoded1

	if len(wrapper.Events) > 0 {
		var __raw2 []json.RawMessage
		if err = json.Unmarshal(wrapper.Events, &__raw2); err != nil {
			return fmt.Errorf("field events: %w", err)
		}
		var __decoded2 []Event
		if __raw2 != nil {
			__decoded2 = make([]Event, len(__raw2))
		}
		for __index, __raw := range __raw2 {
			if __decoded2[__index], err = __jsonUnmarshal__boundary__Event__14033c5e11b7c19bb4b06e0f889fd3440bb71b6e3d80a60245f6e5f100c928f6(__raw); err != nil {
				return fmt.Errorf("field events[%d]: %w", __index, err)
			}
		}
		__next.Events = __decoded2
	}

	if len(wrapper.Extra) > 0 {
		var __decoded3 Event
		if __decoded3, err = __jsonUnmarshal__boundary__Event__14033c5e11b7c19bb4b06e0f889fd3440bb71b6e3d80a60245f6e5f100c928f6(wrapper.Extra); err != nil {
			return err
		}
		__next.Extra.Value = __decoded3
		__next.Extra.Present = true
	}

	*p = __next
	return nil
}

func __jsonschema__isJSONNull(data []byte) bool {
	return bytes.Equal(bytes.TrimSpace(data), []byte("null"))
}
func __jsonMarshal__boundary__Event__9765682108c55bc1ada1376e4af4a6c2cc9965bfab7611e790f53644f0e31217(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "born"
		data, err = json.Marshal(&object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "gone"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"kind",
		discriminator,
	)
}

func __jsonUnmarshal__boundary__Event__9765682108c55bc1ada1376e4af4a6c2cc9965bfab7611e790f53644f0e31217(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "kind")
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "born":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "gone":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonMarshal__boundary__Event__e6e32185f0aa20dcba2a18e25286e1f6d044f1f4e4f7a00366f124a88686d13e(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "new"
		data, err = json.Marshal(&object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "removed"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"!\"kind",
		discriminator,
	)
}

func __jsonUnmarshal__boundary__Event__e6e32185f0aa20dcba2a18e25286e1f6d044f1f4e4f7a00366f124a88686d13e(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!\"kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!\"kind")
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "new":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "removed":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonMarshal__boundary__Event__14033c5e11b7c19bb4b06e0f889fd3440bb71b6e3d80a60245f6e5f100c928f6(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "created"
		data, err = json.Marshal(&object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "deleted"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"type",
		discriminator,
	)
}

func __jsonUnmarshal__boundary__Event__14033c5e11b7c19bb4b06e0f889fd3440bb71b6e3d80a60245f6e5f100c928f6(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		return nil, errNoDiscriminator
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "created":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "deleted":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := json.Marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return json.Marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
