package scaffold_demo

import "testing"

// TestSchemaRuntime is recovered evidence (see
// ephemeral/issue-73/manager-validation/run/events/000001-validate.jsonl,
// event 62) that the validator ran and then discarded: it proves the
// scaffolded fluent Declare(Widget.Schema) registration, once generated by
// the real gen-jsonschema binary, produces a working runtime
// Widget{}.Schema() embedding the expected required-fields contract - not
// just a template that compiles.
func TestSchemaRuntime(t *testing.T) {
	got := Demo()
	want := "[name count]"
	if got != want {
		t.Fatalf("got %s want %s", got, want)
	}
}
