//go:build !jsonschema
// +build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package uniontypes

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property '!type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (Circle) Schema() json.RawMessage {
	const fileName = "jsonschema/Circle.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Rectangle) Schema() json.RawMessage {
	const fileName = "jsonschema/Rectangle.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Triangle) Schema() json.RawMessage {
	const fileName = "jsonschema/Triangle.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Drawing) Schema() json.RawMessage {
	const fileName = "jsonschema/Drawing.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (CreditCard) Schema() json.RawMessage {
	const fileName = "jsonschema/CreditCard.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (BankTransfer) Schema() json.RawMessage {
	const fileName = "jsonschema/BankTransfer.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (*DigitalWallet) Schema() json.RawMessage {
	const fileName = "jsonschema/DigitalWallet.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Payment) Schema() json.RawMessage {
	const fileName = "jsonschema/Payment.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Drawing.
func (d *Drawing) UnmarshalJSON(b []byte) (err error) {
	type Alias Drawing
	type Wrapper struct {
		Alias
		MainShape json.RawMessage `json:"mainShape,omitempty"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(b, &wrapper); err != nil {
		return err
	}
	__next := Drawing(wrapper.Alias)

	if __next.MainShape, err = __jsonUnmarshal__uniontypes__Shape(wrapper.MainShape); err != nil {
		return err
	}

	*d = __next
	return nil
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Payment.
func (p *Payment) UnmarshalJSON(b []byte) (err error) {
	type Alias Payment
	type Wrapper struct {
		Alias
		Method json.RawMessage `json:"method"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(b, &wrapper); err != nil {
		return err
	}
	__next := Payment(wrapper.Alias)

	if __next.Method, err = __jsonUnmarshal__uniontypes__PaymentMethod(wrapper.Method); err != nil {
		return err
	}

	*p = __next
	return nil
}
func __jsonUnmarshal__uniontypes__Shape(data []byte) (Shape, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!type"]; !ok {
		return nil, errNoDiscriminator
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Circle":
		var obj Circle
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Rectangle":
		var obj Rectangle
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Triangle":
		var obj Triangle
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonUnmarshal__uniontypes__PaymentMethod(data []byte) (PaymentMethod, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!type"]; !ok {
		return nil, errNoDiscriminator
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "CreditCard":
		var obj CreditCard
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "BankTransfer":
		var obj BankTransfer
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "DigitalWallet":
		var obj DigitalWallet
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
