//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package adoptiontransport

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Shipment *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Shipment
		__gen_jsonschema_compiled_Shipment = compile("Shipment", __zero.Schema())
	}
}

func (Shipment) Schema() json.RawMessage {
	const fileName = "jsonschema/Shipment.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Shipment.
func (Shipment) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Shipment.Validate(inst)
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Shipment.
func (s Shipment) MarshalJSON() ([]byte, error) {
	type Alias Shipment
	type Wrapper struct {
		Alias
		Event  json.RawMessage `json:"event"`
		Status json.RawMessage `json:"status"`
	}
	wrapper := Wrapper{Alias: Alias(s)}
	var err error

	if wrapper.Event, err = __jsonMarshal__adoptiontransport__ShipmentEvent__5e0fcd949db1397bab1858223e8ae6f91cbfe73a2fcd1dcae46b80f6b2e583ab(s.Event); err != nil {
		return nil, fmt.Errorf("field event: %w", err)
	}

	if wrapper.Status, err = __jsonMarshalEnum__Shipment__Status(s.Status); err != nil {
		return nil, fmt.Errorf("field status: %w", err)
	}

	return json.Marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Shipment.
func (s *Shipment) UnmarshalJSON(data []byte) (err error) {
	type Alias Shipment
	type Wrapper struct {
		Alias
		Event  json.RawMessage `json:"event"`
		Status json.RawMessage `json:"status"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Shipment(wrapper.Alias)

	var __decoded0 ShipmentEvent
	if __decoded0, err = __jsonUnmarshal__adoptiontransport__ShipmentEvent__5e0fcd949db1397bab1858223e8ae6f91cbfe73a2fcd1dcae46b80f6b2e583ab(wrapper.Event); err != nil {
		return err
	}
	__next.Event = __decoded0

	var __enumDecoded0 Status
	if __enumDecoded0, err = __jsonUnmarshalEnum__Shipment__Status(wrapper.Status); err != nil {
		return fmt.Errorf("field status: %w", err)
	}
	__next.Status = __enumDecoded0

	*s = __next
	return nil
}

func __jsonMarshalEnum__Shipment__Status(value Status) (json.RawMessage, error) {
	switch value {
	case StatusUnknown:
		return json.Marshal("StatusUnknown")
	case StatusReady:
		return json.Marshal("StatusReady")
	case StatusDelivered:
		return json.Marshal("StatusDelivered")
	default:
		return nil, errors.New("undeclared value for string-mode enum Status")
	}
}

func __jsonUnmarshalEnum__Shipment__Status(data []byte) (Status, error) {
	var zero Status
	if __jsonschema__isJSONNull(data) {
		return zero, errors.New("string-mode enum Status cannot be JSON null")
	}
	var wire string
	if err := json.Unmarshal(data, &wire); err != nil {
		return zero, fmt.Errorf("string-mode enum Status requires a JSON string: %w", err)
	}
	switch wire {
	case "StatusUnknown":
		return StatusUnknown, nil
	case "StatusReady":
		return StatusReady, nil
	case "StatusDelivered":
		return StatusDelivered, nil
	default:
		return zero, fmt.Errorf("unknown string-mode enum Status name %q", wire)
	}
}
func __jsonschema__isJSONNull(data []byte) bool {
	return bytes.Equal(bytes.TrimSpace(data), []byte("null"))
}
func __jsonMarshal__adoptiontransport__ShipmentEvent__5e0fcd949db1397bab1858223e8ae6f91cbfe73a2fcd1dcae46b80f6b2e583ab(value ShipmentEvent) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface ShipmentEvent")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "created"
		data, err = json.Marshal(&object)
	case Dispatched:
		discriminator = "dispatched"
		data, err = json.Marshal(&object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for ShipmentEvent", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for ShipmentEvent: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"kind",
		discriminator,
	)
}

func __jsonUnmarshal__adoptiontransport__ShipmentEvent__5e0fcd949db1397bab1858223e8ae6f91cbfe73a2fcd1dcae46b80f6b2e583ab(data []byte) (ShipmentEvent, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "kind")
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "created":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "dispatched":
		var obj Dispatched
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := json.Marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return json.Marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
