//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package ptrfixture

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"text/template"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (*Thing) Schema() json.RawMessage {
	const fileName = "jsonschema/Thing.json.tmpl"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (t *Thing) RenderedSchema() (json.RawMessage, error) {
	const fileName = "jsonschema/Thing.json.tmpl"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	ctx := map[string]string{}
	// provider for Name
	{
		var __prov json.Marshaler
		__prov = t.NameSchema()
		__b, __err := __prov.MarshalJSON()
		if __err != nil {
			return nil, __err
		}
		ctx["name"] = string(__b)
	}
	// provider for Count
	{
		var __prov json.Marshaler
		__prov = t.CountSchema(t.Count)
		__b, __err := __prov.MarshalJSON()
		if __err != nil {
			return nil, __err
		}
		ctx["count"] = string(__b)
	}
	tpl, err := template.New("schema").Option("missingkey=error").Parse(string(data))
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, ctx); err != nil {
		return nil, err
	}
	return json.RawMessage(buf.Bytes()), nil
}
