//go:build !jsonschema
// +build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package entrypoints

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property '!type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_MethodType  *jsonschema.Schema
	__gen_jsonschema_compiled_FuncType    *jsonschema.Schema
	__gen_jsonschema_compiled_BuilderType *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero MethodType
		__gen_jsonschema_compiled_MethodType = compile("MethodType", __zero.Schema())
	}

	{
		var __zero FuncType
		__gen_jsonschema_compiled_FuncType = compile("FuncType", __zero.FuncTypeSchema())
	}

	{
		var __zero BuilderType
		__gen_jsonschema_compiled_BuilderType = compile("BuilderType", __zero.BuilderTypeSchema())
	}
}

func (MethodType) Schema() json.RawMessage {
	const fileName = "jsonschema/MethodType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (FuncType) FuncTypeSchema() json.RawMessage {
	const fileName = "jsonschema/FuncType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (BuilderType) BuilderTypeSchema() json.RawMessage {
	const fileName = "jsonschema/BuilderType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for MethodType.
func (MethodType) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_MethodType.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for FuncType.
func (FuncType) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_FuncType.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for BuilderType.
func (BuilderType) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_BuilderType.Validate(inst)
}
