//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package interfaces

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	yaml "go.yaml.in/yaml/v4"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __gen_jsonschema_yamlNodeToJSON(node *yaml.Node) ([]byte, error) {
	var value any
	if err := node.Decode(&value); err != nil {
		return nil, err
	}
	return json.Marshal(value)
}

func (FancyStruct) Schema() json.RawMessage {
	const fileName = "jsonschema/FancyStruct.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// FancyStruct.
func (f FancyStruct) MarshalJSON() ([]byte, error) {
	type Alias FancyStruct
	type Wrapper struct {
		Alias
		IFace  json.RawMessage `json:"iface"`
		IFaces json.RawMessage `json:"ifaces"`
	}
	wrapper := Wrapper{Alias: Alias(f)}
	var err error

	if wrapper.IFace, err = __jsonMarshal__interfaces__TestInterface(f.IFace); err != nil {
		return nil, fmt.Errorf("field iface: %w", err)
	}

	if f.IFaces == nil {
		return nil, fmt.Errorf("field ifaces: nil registered interface slice")
	}
	__raw1 := make([]json.RawMessage, len(f.IFaces))
	for __index, __value := range f.IFaces {
		if __raw1[__index], err = __jsonMarshal__interfaces__TestInterface(__value); err != nil {
			return nil, fmt.Errorf("field ifaces[%d]: %w", __index, err)
		}
	}
	if wrapper.IFaces, err = json.Marshal(__raw1); err != nil {
		return nil, fmt.Errorf("field ifaces: %w", err)
	}

	return json.Marshal(wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// FancyStruct.
func (f *FancyStruct) UnmarshalJSON(data []byte) (err error) {
	type Alias FancyStruct
	type Wrapper struct {
		Alias
		IFace  json.RawMessage `json:"iface"`
		IFaces json.RawMessage `json:"ifaces"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := FancyStruct(wrapper.Alias)

	var __decoded0 TestInterface
	if __decoded0, err = __jsonUnmarshal__interfaces__TestInterface(wrapper.IFace); err != nil {
		return err
	}
	__next.IFace = __decoded0

	if len(wrapper.IFaces) > 0 {
		var __raw1 []json.RawMessage
		if err = json.Unmarshal(wrapper.IFaces, &__raw1); err != nil {
			return fmt.Errorf("field ifaces: %w", err)
		}
		var __decoded1 []TestInterface
		if __raw1 != nil {
			__decoded1 = make([]TestInterface, len(__raw1))
		}
		for __index, __raw := range __raw1 {
			if __decoded1[__index], err = __jsonUnmarshal__interfaces__TestInterface(__raw); err != nil {
				return fmt.Errorf("field ifaces[%d]: %w", __index, err)
			}
		}
		__next.IFaces = __decoded1
	}

	*f = __next
	return nil
}

// UnmarshalYAML translates YAML into the JSON data model before decoding
// FancyStruct with its JSON contract.
func (f *FancyStruct) UnmarshalYAML(node *yaml.Node) error {
	data, err := __gen_jsonschema_yamlNodeToJSON(node)
	if err != nil {
		return err
	}
	var next FancyStruct
	if err := json.Unmarshal(data, &next); err != nil {
		return err
	}
	*f = next
	return nil
}
func __jsonMarshal__interfaces__TestInterface(value TestInterface) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface TestInterface")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case TestInterface1:
		discriminator = "TestInterface1"
		data, err = json.Marshal(object)
	case TestInterface2:
		discriminator = "TestInterface2"
		data, err = json.Marshal(object)
	case *PointerToTestInterface:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for TestInterface", value)
		}
		discriminator = "PointerToTestInterface"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for TestInterface", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for TestInterface: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"type",
		discriminator,
	)
}

func __jsonUnmarshal__interfaces__TestInterface(data []byte) (TestInterface, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		return nil, errNoDiscriminator
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "TestInterface1":
		var obj TestInterface1
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "TestInterface2":
		var obj TestInterface2
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "PointerToTestInterface":
		var obj PointerToTestInterface
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		var current string
		if err := json.Unmarshal(encoded, &current); err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := json.Marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return json.Marshal(object)
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
