//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package messages

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	yaml "go.yaml.in/yaml/v4"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property '!type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (ToolFuncGetTypeInfo) Schema() json.RawMessage {
	const fileName = "jsonschema/ToolFuncGetTypeInfo.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (GeneratedTestResponse) Schema() json.RawMessage {
	const fileName = "jsonschema/GeneratedTestResponse.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Assertion.
func (a *Assertion) UnmarshalJSON(data []byte) (err error) {
	type Alias Assertion
	type Wrapper struct {
		Alias
		Value json.RawMessage `json:"value"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Assertion(wrapper.Alias)

	if __next.Value, err = __jsonUnmarshal__messages__AssertionValue(wrapper.Value); err != nil {
		return err
	}

	*a = __next
	return nil
}

// UnmarshalYAML is a generated custom yaml.Unmarshaler implementation for
// Assertion.
func (a *Assertion) UnmarshalYAML(node *yaml.Node) (err error) {
	var fields map[string]yaml.Node
	if err = node.Decode(&fields); err != nil {
		return err
	}
	ordinary := make(map[string]yaml.Node, len(fields))
	for name, value := range fields {
		ordinary[name] = value
	}
	delete(ordinary, "value")
	type Alias Assertion
	var alias Alias
	ordinaryNode := __jsonschema__yamlMappingNode(ordinary)
	if err = ordinaryNode.Decode(&alias); err != nil {
		return err
	}
	__next := Assertion(alias)

	__node0 := fields["value"]
	if __next.Value, err = __yamlUnmarshal__messages__AssertionValue(&__node0); err != nil {
		return err
	}

	*a = __next
	return nil
}
func __jsonUnmarshal__messages__AssertionValue(data []byte) (AssertionValue, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!type"]; !ok {
		return nil, errNoDiscriminator
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "AssertNumericValue":
		var obj AssertNumericValue
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertStringValue":
		var obj AssertStringValue
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertBoolValue":
		var obj AssertBoolValue
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertType":
		var obj AssertType
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertArrayLength":
		var obj AssertArrayLength
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __yamlUnmarshal__messages__AssertionValue(node *yaml.Node) (AssertionValue, error) {
	var temp map[string]yaml.Node
	if err := node.Decode(&temp); err != nil {
		return nil, err
	}
	discriminatorNode, ok := temp["!type"]
	if !ok {
		return nil, errNoDiscriminator
	}
	var discriminator string
	if err := discriminatorNode.Decode(&discriminator); err != nil {
		return nil, fmt.Errorf("unable to unmarshal discriminator value %q: %w", discriminatorNode.Value, err)
	}
	switch discriminator {
	case "AssertNumericValue":
		var obj AssertNumericValue
		if err := node.Decode(&obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertStringValue":
		var obj AssertStringValue
		if err := node.Decode(&obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertBoolValue":
		var obj AssertBoolValue
		if err := node.Decode(&obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertType":
		var obj AssertType
		if err := node.Decode(&obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertArrayLength":
		var obj AssertArrayLength
		if err := node.Decode(&obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}

func __jsonschema__yamlMappingNode(fields map[string]yaml.Node) yaml.Node {
	content := make([]*yaml.Node, 0, len(fields)*2)
	for name, value := range fields {
		nameNode := yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: name}
		valueNode := value
		content = append(content, &nameNode, &valueNode)
	}
	return yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", Content: content}
}
