//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package union_codec

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Envelope *jsonschema.Schema
	__gen_jsonschema_compiled_Nested   *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Envelope
		__gen_jsonschema_compiled_Envelope = compile("Envelope", __zero.Schema())
	}

	{
		var __zero Nested
		__gen_jsonschema_compiled_Nested = compile("Nested", __zero.Schema())
	}
}

func (Envelope) Schema() json.RawMessage {
	const fileName = "jsonschema/Envelope.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Nested) Schema() json.RawMessage {
	const fileName = "jsonschema/Nested.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Envelope.
func (Envelope) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Envelope.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Nested.
func (Nested) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Nested.Validate(inst)
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Envelope.
func (e Envelope) MarshalJSON() ([]byte, error) {
	type Alias Envelope
	type Wrapper struct {
		Alias
		Primary   json.RawMessage `json:"primary"`
		Events    json.RawMessage `json:"events"`
		Optional  json.RawMessage `json:"optional,omitzero"`
		Alternate json.RawMessage `json:"alternate,omitzero"`
		Single    json.RawMessage `json:"single,omitzero"`
		Hook      json.RawMessage `json:"hook,omitzero"`
	}
	wrapper := Wrapper{Alias: Alias(e)}
	var err error

	if wrapper.Primary, err = __jsonMarshal__union_codec__Event__Envelope__Primary(e.Primary); err != nil {
		return nil, fmt.Errorf("field primary: %w", err)
	}

	if e.Events == nil {
		return nil, fmt.Errorf("field events: nil registered interface slice")
	}
	__raw1 := make([]json.RawMessage, len(e.Events))
	for __index, __value := range e.Events {
		if __raw1[__index], err = __jsonMarshal__union_codec__Event__Envelope__Events(__value); err != nil {
			return nil, fmt.Errorf("field events[%d]: %w", __index, err)
		}
	}
	if wrapper.Events, err = json.Marshal(__raw1); err != nil {
		return nil, fmt.Errorf("field events: %w", err)
	}

	if e.Optional.Present {
		if wrapper.Optional, err = __jsonMarshal__union_codec__Event__Envelope__Optional(e.Optional.Value); err != nil {
			return nil, fmt.Errorf("field optional: %w", err)
		}
	}

	if e.Alternate.Present {
		if wrapper.Alternate, err = __jsonMarshal__union_codec__Event__Envelope__Alternate(e.Alternate.Value); err != nil {
			return nil, fmt.Errorf("field alternate: %w", err)
		}
	}

	if e.Single.Present {
		if wrapper.Single, err = __jsonMarshal__union_codec__Event__Envelope__Single(e.Single.Value); err != nil {
			return nil, fmt.Errorf("field single: %w", err)
		}
	}

	if e.Hook.Present {
		if wrapper.Hook, err = __jsonMarshal__union_codec__Event__Envelope__Hook(e.Hook.Value); err != nil {
			return nil, fmt.Errorf("field hook: %w", err)
		}
	}

	return json.Marshal(wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Envelope.
func (e *Envelope) UnmarshalJSON(data []byte) (err error) {
	type Alias Envelope
	type Wrapper struct {
		Alias
		Primary   json.RawMessage `json:"primary"`
		Events    json.RawMessage `json:"events"`
		Optional  json.RawMessage `json:"optional,omitzero"`
		Alternate json.RawMessage `json:"alternate,omitzero"`
		Single    json.RawMessage `json:"single,omitzero"`
		Hook      json.RawMessage `json:"hook,omitzero"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Envelope(wrapper.Alias)

	var __decoded0 Event
	if __decoded0, err = __jsonUnmarshal__union_codec__Event__Envelope__Primary(wrapper.Primary); err != nil {
		return err
	}
	__next.Primary = __decoded0

	if len(wrapper.Events) > 0 {
		var __raw1 []json.RawMessage
		if err = json.Unmarshal(wrapper.Events, &__raw1); err != nil {
			return fmt.Errorf("field events: %w", err)
		}
		var __decoded1 []Event
		if __raw1 != nil {
			__decoded1 = make([]Event, len(__raw1))
		}
		for __index, __raw := range __raw1 {
			if __decoded1[__index], err = __jsonUnmarshal__union_codec__Event__Envelope__Events(__raw); err != nil {
				return fmt.Errorf("field events[%d]: %w", __index, err)
			}
		}
		__next.Events = __decoded1
	}

	if len(wrapper.Optional) > 0 {
		var __decoded2 Event
		if __decoded2, err = __jsonUnmarshal__union_codec__Event__Envelope__Optional(wrapper.Optional); err != nil {
			return err
		}
		__next.Optional.Value = __decoded2
		__next.Optional.Present = true
	}

	if len(wrapper.Alternate) > 0 {
		var __decoded3 Event
		if __decoded3, err = __jsonUnmarshal__union_codec__Event__Envelope__Alternate(wrapper.Alternate); err != nil {
			return err
		}
		__next.Alternate.Value = __decoded3
		__next.Alternate.Present = true
	}

	if len(wrapper.Single) > 0 {
		var __decoded4 Event
		if __decoded4, err = __jsonUnmarshal__union_codec__Event__Envelope__Single(wrapper.Single); err != nil {
			return err
		}
		__next.Single.Value = __decoded4
		__next.Single.Present = true
	}

	if len(wrapper.Hook) > 0 {
		var __decoded5 Event
		if __decoded5, err = __jsonUnmarshal__union_codec__Event__Envelope__Hook(wrapper.Hook); err != nil {
			return err
		}
		__next.Hook.Value = __decoded5
		__next.Hook.Present = true
	}

	*e = __next
	return nil
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Nested.
func (n Nested) MarshalJSON() ([]byte, error) {
	type Alias Nested
	type Wrapper struct {
		Alias
		Event json.RawMessage `json:"event"`
	}
	wrapper := Wrapper{Alias: Alias(n)}
	var err error

	if wrapper.Event, err = __jsonMarshal__union_codec__Event__Nested__Event(n.Event); err != nil {
		return nil, fmt.Errorf("field event: %w", err)
	}

	return json.Marshal(wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Nested.
func (n *Nested) UnmarshalJSON(data []byte) (err error) {
	type Alias Nested
	type Wrapper struct {
		Alias
		Event json.RawMessage `json:"event"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Nested(wrapper.Alias)

	var __decoded0 Event
	if __decoded0, err = __jsonUnmarshal__union_codec__Event__Nested__Event(wrapper.Event); err != nil {
		return err
	}
	__next.Event = __decoded0

	*n = __next
	return nil
}
func __jsonMarshal__union_codec__Event__Envelope__Primary(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "created"
		data, err = json.Marshal(object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "deleted"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"!kind",
		discriminator,
	)
}

func __jsonUnmarshal__union_codec__Event__Envelope__Primary(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "created":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "deleted":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonMarshal__union_codec__Event__Envelope__Events(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "Created"
		data, err = json.Marshal(object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "Deleted"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"type",
		discriminator,
	)
}

func __jsonUnmarshal__union_codec__Event__Envelope__Events(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		return nil, errNoDiscriminator
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Created":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Deleted":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonMarshal__union_codec__Event__Envelope__Optional(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "Created"
		data, err = json.Marshal(object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "Deleted"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"type",
		discriminator,
	)
}

func __jsonUnmarshal__union_codec__Event__Envelope__Optional(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		return nil, errNoDiscriminator
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Created":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Deleted":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonMarshal__union_codec__Event__Envelope__Alternate(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "new\"event"
		data, err = json.Marshal(object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "gone"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"kind\"quoted",
		discriminator,
	)
}

func __jsonUnmarshal__union_codec__Event__Envelope__Alternate(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["kind\"quoted"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "kind\"quoted")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "new\"event":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "gone":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonMarshal__union_codec__Event__Envelope__Single(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "only"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"single",
		discriminator,
	)
}

func __jsonUnmarshal__union_codec__Event__Envelope__Single(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["single"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "single")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "only":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonMarshal__union_codec__Event__Envelope__Hook(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Hooked:
		discriminator = "hooked"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"hookKind",
		discriminator,
	)
}

func __jsonUnmarshal__union_codec__Event__Envelope__Hook(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["hookKind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "hookKind")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "hooked":
		var obj Hooked
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonMarshal__union_codec__Event__Nested__Event(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "nested-created"
		data, err = json.Marshal(object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "nested-deleted"
		data, err = json.Marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"nestedKind",
		discriminator,
	)
}

func __jsonUnmarshal__union_codec__Event__Nested__Event(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["nestedKind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "nestedKind")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "nested-created":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "nested-deleted":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		var current string
		if err := json.Unmarshal(encoded, &current); err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := json.Marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return json.Marshal(object)
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
