package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const (
	manifestPath = "internal/cmd/doc-gen/skill-examples.json"
	outputPath   = "skills/go-gen-jsonschema/references/examples.md"
)

type manifest struct {
	Examples []example `json:"examples"`
}

type example struct {
	ID       string    `json:"id"`
	Title    string    `json:"title"`
	When     string    `json:"when"`
	Sections []section `json:"sections"`
}

type section struct {
	Source        string   `json:"source"`
	Declarations  []string `json:"declarations,omitempty"`
	Registrations []string `json:"registrations,omitempty"`
}

func main() {
	check := flag.Bool("check", false, "fail if the checked-in reference is stale")
	flag.Parse()

	root, err := repositoryRoot()
	if err != nil {
		fatal(err)
	}
	contents, err := generate(root, filepath.Join(root, manifestPath))
	if err != nil {
		fatal(err)
	}
	destination := filepath.Join(root, outputPath)
	if *check {
		current, err := os.ReadFile(destination)
		if err != nil {
			fatal(err)
		}
		if !bytes.Equal(current, contents) {
			fatal(fmt.Errorf("stale generated reference at %s", outputPath))
		}
		return
	}
	if err := writeIfChanged(destination, contents); err != nil {
		fatal(err)
	}
}

func repositoryRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		} else if !errors.Is(err, os.ErrNotExist) {
			return "", err
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("could not find repository root containing go.mod")
		}
		dir = parent
	}
}

func generate(root, path string) ([]byte, error) {
	m, err := loadManifest(path)
	if err != nil {
		return nil, err
	}
	var out bytes.Buffer
	out.WriteString("# Examples\n\n")
	out.WriteString("<!-- Code generated by internal/cmd/doc-gen; DO NOT EDIT. -->\n\n")
	out.WriteString("These examples are selected from compiling repository source. Follow the source links for surrounding context.\n")
	for _, ex := range m.Examples {
		fmt.Fprintf(&out, "\n## %s\n\n%s\n", ex.Title, ex.When)
		for _, sec := range ex.Sections {
			snippets, err := extract(filepath.Join(root, filepath.FromSlash(sec.Source)), sec)
			if err != nil {
				return nil, fmt.Errorf("example %q: %w", ex.ID, err)
			}
			fmt.Fprintf(&out, "\nSource: [`%s`](../../../%s)\n\n```go\n", sec.Source, sec.Source)
			for i, snippet := range snippets {
				if i > 0 {
					out.WriteByte('\n')
				}
				out.Write(snippet)
			}
			out.WriteString("```\n")
		}
	}
	return out.Bytes(), nil
}

func loadManifest(path string) (manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return manifest{}, err
	}
	var m manifest
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&m); err != nil {
		return manifest{}, fmt.Errorf("parse manifest: %w", err)
	}
	seen := make(map[string]bool)
	for i, ex := range m.Examples {
		if ex.ID == "" || ex.Title == "" || ex.When == "" || len(ex.Sections) == 0 {
			return manifest{}, fmt.Errorf("example %d must have id, title, when, and sections", i)
		}
		if seen[ex.ID] {
			return manifest{}, fmt.Errorf("duplicate example id %q", ex.ID)
		}
		seen[ex.ID] = true
		for j, sec := range ex.Sections {
			if sec.Source == "" || len(sec.Declarations)+len(sec.Registrations) == 0 {
				return manifest{}, fmt.Errorf("example %q section %d must have a source and selections", ex.ID, j)
			}
		}
	}
	return m, nil
}

func extract(path string, selection section) ([][]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", selection.Source, err)
	}
	wantedDecls := toSet(selection.Declarations)
	wantedRegs := toSet(selection.Registrations)
	foundDecls := make(map[string]bool)
	foundRegs := make(map[string]bool)
	var snippets [][]byte
	for _, decl := range file.Decls {
		matched := false
		for _, name := range declarationNames(decl) {
			if wantedDecls[name] {
				foundDecls[name] = true
				matched = true
			}
		}
		for _, name := range registrationNames(decl) {
			if wantedRegs[name] {
				foundRegs[name] = true
				matched = true
			}
		}
		if !matched {
			continue
		}
		var formatted bytes.Buffer
		if err := format.Node(&formatted, fset, decl); err != nil {
			return nil, fmt.Errorf("format selection from %s: %w", selection.Source, err)
		}
		formatted.WriteByte('\n')
		snippets = append(snippets, formatted.Bytes())
	}
	if missing := missingSelections(selection.Declarations, foundDecls); len(missing) > 0 {
		return nil, fmt.Errorf("missing declarations in %s: %s", selection.Source, strings.Join(missing, ", "))
	}
	if missing := missingSelections(selection.Registrations, foundRegs); len(missing) > 0 {
		return nil, fmt.Errorf("missing registrations in %s: %s", selection.Source, strings.Join(missing, ", "))
	}
	return snippets, nil
}

func declarationNames(decl ast.Decl) []string {
	switch d := decl.(type) {
	case *ast.FuncDecl:
		if d.Recv == nil {
			return []string{d.Name.Name}
		}
		if receiver := receiverName(d.Recv.List[0].Type); receiver != "" {
			return []string{receiver + "." + d.Name.Name}
		}
	case *ast.GenDecl:
		var names []string
		for _, spec := range d.Specs {
			switch s := spec.(type) {
			case *ast.TypeSpec:
				names = append(names, s.Name.Name)
			case *ast.ValueSpec:
				for _, name := range s.Names {
					names = append(names, name.Name)
				}
			}
		}
		return names
	}
	return nil
}

func receiverName(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return receiverName(e.X)
	case *ast.IndexExpr:
		return receiverName(e.X)
	case *ast.IndexListExpr:
		return receiverName(e.X)
	}
	return ""
}

func registrationNames(decl ast.Decl) []string {
	gen, ok := decl.(*ast.GenDecl)
	if !ok || gen.Tok != token.VAR {
		return nil
	}
	var names []string
	for _, spec := range gen.Specs {
		valueSpec, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}
		for _, value := range valueSpec.Values {
			call, ok := value.(*ast.CallExpr)
			if !ok || !isRegistrationCall(call.Fun) || len(call.Args) == 0 {
				continue
			}
			selector, ok := call.Args[0].(*ast.SelectorExpr)
			if !ok {
				continue
			}
			receiver, ok := selector.X.(*ast.Ident)
			if ok {
				names = append(names, receiver.Name+"."+selector.Sel.Name)
			}
		}
	}
	return names
}

func isRegistrationCall(expr ast.Expr) bool {
	var name string
	switch e := expr.(type) {
	case *ast.Ident:
		name = e.Name
	case *ast.SelectorExpr:
		name = e.Sel.Name
	}
	return name == "NewJSONSchemaMethod" || name == "NewJSONSchemaFunc"
}

func toSet(values []string) map[string]bool {
	set := make(map[string]bool, len(values))
	for _, value := range values {
		set[value] = true
	}
	return set
}

func missingSelections(wanted []string, found map[string]bool) []string {
	var missing []string
	for _, name := range wanted {
		if !found[name] {
			missing = append(missing, name)
		}
	}
	return missing
}

func writeIfChanged(path string, contents []byte) error {
	current, err := os.ReadFile(path)
	if err == nil && bytes.Equal(current, contents) {
		return nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return os.WriteFile(path, contents, 0o644)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "doc-gen:", err)
	os.Exit(1)
}
