//go:build !jsonschema

// Code generated by go-gen-jsonschema. DO NOT EDIT.
package v1_interfaces_options

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	yaml "go.yaml.in/yaml/v4"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __gen_jsonschema_yamlNodeToJSON(node *yaml.Node) ([]byte, error) {
	var value any
	if err := node.Decode(&value); err != nil {
		return nil, err
	}
	return json.Marshal(value)
}

func __gen_jsonschema_yamlToJSON(data []byte) ([]byte, error) {
	var value any
	if err := yaml.Load(data, &value, yaml.WithV4Defaults()); err != nil {
		return nil, err
	}
	return json.Marshal(value)
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Plain *jsonschema.Schema
	__gen_jsonschema_compiled_Owner *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("go-gen-jsonschema: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Plain
		__gen_jsonschema_compiled_Plain = compile("Plain", __zero.Schema())
	}

	{
		var __zero Owner
		__gen_jsonschema_compiled_Owner = compile("Owner", __zero.Schema())
	}
}

func (Plain) Schema() json.RawMessage {
	const fileName = "jsonschema/Plain.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Owner) Schema() json.RawMessage {
	const fileName = "jsonschema/Owner.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Plain.
func (Plain) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Plain.Validate(inst)
}

// ValidateYAML validates YAML against the JSON Schema for Plain.
// YAML is interpreted using the schema's JSON property names.
func (Plain) ValidateYAML(data []byte) error {
	jsonData, err := __gen_jsonschema_yamlToJSON(data)
	if err != nil {
		return err
	}
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(jsonData))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Plain.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Owner.
func (Owner) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Owner.Validate(inst)
}

// ValidateYAML validates YAML against the JSON Schema for Owner.
// YAML is interpreted using the schema's JSON property names.
func (Owner) ValidateYAML(data []byte) error {
	jsonData, err := __gen_jsonschema_yamlToJSON(data)
	if err != nil {
		return err
	}
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(jsonData))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Owner.Validate(inst)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Owner.
func (o *Owner) UnmarshalJSON(data []byte) (err error) {
	type Alias Owner
	type Wrapper struct {
		Alias
		IF         json.RawMessage `json:"if" yaml:"yaml_if"`
		IFaces     json.RawMessage `json:"ifs" yaml:"yaml_ifs"`
		OptionalIF json.RawMessage `json:"optional_if,omitzero" yaml:"yaml_optional"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Owner(wrapper.Alias)

	if __next.IF, err = __jsonUnmarshal__v1_interfaces_options__IFace__Owner__IF(wrapper.IF); err != nil {
		return err
	}

	if len(wrapper.IFaces) == 0 {
		__next.IFaces = o.IFaces
	} else {
		var __raw1 []json.RawMessage
		if err = json.Unmarshal(wrapper.IFaces, &__raw1); err != nil {
			return fmt.Errorf("field ifs: %w", err)
		}
		var __decoded1 []IFace
		if __raw1 != nil {
			__decoded1 = make([]IFace, len(__raw1))
		}
		for __index, __raw := range __raw1 {
			if __decoded1[__index], err = __jsonUnmarshal__v1_interfaces_options__IFace__Owner__IFaces(__raw); err != nil {
				return fmt.Errorf("field ifs[%d]: %w", __index, err)
			}
		}
		__next.IFaces = __decoded1
	}

	if len(wrapper.OptionalIF) > 0 {
		if __next.OptionalIF.Value, err = __jsonUnmarshal__v1_interfaces_options__IFace__Owner__OptionalIF(wrapper.OptionalIF); err != nil {
			return err
		}
		__next.OptionalIF.Present = true
	}

	*o = __next
	return nil
}

// UnmarshalYAML translates YAML into the JSON data model before decoding
// Owner with its JSON contract.
func (o *Owner) UnmarshalYAML(node *yaml.Node) error {
	data, err := __gen_jsonschema_yamlNodeToJSON(node)
	if err != nil {
		return err
	}
	var next Owner
	if err := json.Unmarshal(data, &next); err != nil {
		return err
	}
	*o = next
	return nil
}

// UnmarshalYAML translates YAML into the JSON data model before decoding
// Plain with its JSON contract.
func (p *Plain) UnmarshalYAML(node *yaml.Node) error {
	data, err := __gen_jsonschema_yamlNodeToJSON(node)
	if err != nil {
		return err
	}
	var next Plain
	if err := json.Unmarshal(data, &next); err != nil {
		return err
	}
	*p = next
	return nil
}
func __jsonUnmarshal__v1_interfaces_options__IFace__Owner__IF(data []byte) (IFace, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "impl_one":
		var obj Impl1
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "impl \"two\"":
		var obj Impl2
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonUnmarshal__v1_interfaces_options__IFace__Owner__IFaces(data []byte) (IFace, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Impl1":
		var obj Impl1
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Impl2":
		var obj Impl2
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonUnmarshal__v1_interfaces_options__IFace__Owner__OptionalIF(data []byte) (IFace, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if err = json.Unmarshal(_tempDiscriminator, &discriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Impl1":
		var obj Impl1
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Impl2":
		var obj Impl2
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
